### PR TITLE
add decode stream

### PR DESCRIPTION
**Pull request by juliangruber**
to replace
- https://github.com/rvagg/node-levelup/blob/master/lib/levelup.js#L372-L387
- https://github.com/rvagg/node-levelup/blob/use/level-iterator-stream/lib/read-stream.js#L23-L37

will be used in levelup like:

``` js
function createReadStream(){
  return iteratorStream(db)
    .pipe(codec.createDecodeStream())
}
```

### CODE REVIEW

**Comment by ralphtheninja** [comment]
:+1:

**Comment by dominictarr** [comment]
one thing here that will probably be a problem at some point is that stream2 are _always async_ so although all that the decode stream is doing is parsing a thing, it still adds a next tick, and this sort of thing can create races. Also stream2#pipe doesn't propagate errors, so pipeing and returning the destination stream isn't always the best way to compose streams because now there is no way for the user to get a handle on errors which may be emitted by the source.

**Comment by juliangruber** [comment]
@dominictarr are you referring to https://github.com/rvagg/node-levelup/pull/321?

We could have a `.createDecodeStream(source)` but that's not ideomatic IMO.

> one thing here that will probably be a problem at some point is that stream2 are always async so although all that the decode stream is doing is parsing a thing, it still adds a next tick, and this sort of thing can create races.

I'm open for suggestions, do you want to for example use pull-streams?

**Comment by dominictarr** [comment]
pull-stream do handle this case better, but streams2 are standard (for better or worse) so I don't think that is the correct answer.

taking the stream as an arguement and mutating it or wrapping it in something is bound to introduce weirdness too.

I think the better answer would be to have a `setDecoder(codec)` method on levelup streams, which would decode the raw event before emitting it.

**Comment by mcollina** [comment]
I'm with Dominic. Also I think the deocode stream would be slower
Il giorno dom 19 apr 2015 alle 01:24 Dominic Tarr notifications@github.com
ha scritto:

**Comment by juliangruber** [comment]
let's just benchmark this, but first we need benchmarks for this in levelup (we only have get, put and batch)

**Comment by juliangruber** [comment]
Ok yeah this is currently ~50% as fast as the old implementation. I'll try this api next:

``` js
function createReadStream(){
  return iteratorStream(db, codec.createStreamDecoder(opts))
}
```

**Comment by juliangruber** [comment]
yes, that implementation for some reason is even faster. i'll come up with a proper pr

**Pull request merged**
