### PR TITLE
Add stream decoder

### PR DESCRIPTION
**Pull request by juliangruber**
This adds a new method `.createStreamDecoder([opts])` which decodes key/value pairs and returns what you need (eg if you pass `{ keys: true }`, only the key will be returned).

We discovered the need for this in https://github.com/Level/codec/pull/5

@ralphtheninja @dominictarr @mcollina

### CODE REVIEW

**Comment by jcrugzz** [comment]
this LGTM @juliangruber.

**Comment by ralphtheninja** [comment]
lgtm!

**Comment by juliangruber** [comment]
i'll merge once https://github.com/rvagg/node-levelup/pull/321 works. thanks for reviewing :)

**Comment by mcollina** [comment]
LGTM.
Il giorno mar 21 apr 2015 alle 22:14 Julian Gruber notifications@github.com
ha scritto:

**Comment by juliangruber** [comment]
6.0.0

**Pull request merged**
